version: '3.2'
services:
  web:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"

networks:
  default:
    external:
      name: beekeeperstack_default
